buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://mirrors.huaweicloud.com/repository/maven/' }
        maven { url 'https://didi.github.io/maven/' }
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.22'
        classpath 'io.github.didi.dokit:dokitx-plugin:3.5.0'
    }
}
