[versions]
agp = "9.1.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
dokit = "3.5.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
dokitx = { group = "io.github.didi.dokit", name = "dokitx", version.ref = "dokit" }
dokitx-no-op = { group = "io.github.didi.dokit", name = "dokitx-no-op", version.ref = "dokit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

