[versions]
agp = "9.1.1"
room = "2.8.4"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
dokit = "3.5.0"
matrix = "2.1.0"
leakcanary = "2.14"
metricsPerformance = "1.0.0"
tracing = "1.3.0"
godeye = "3.4.3"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
dokitx = { group = "io.github.didi.dokit", name = "dokitx", version.ref = "dokit" }
dokitx-no-op = { group = "io.github.didi.dokit", name = "dokitx-no-op", version.ref = "dokit" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
matrix-android-lib = { group = "com.tencent.matrix", name = "matrix-android-lib", version.ref = "matrix" }
matrix-android-commons = { group = "com.tencent.matrix", name = "matrix-android-commons", version.ref = "matrix" }
matrix-trace-canary = { group = "com.tencent.matrix", name = "matrix-trace-canary", version.ref = "matrix" }
matrix-io-canary = { group = "com.tencent.matrix", name = "matrix-io-canary", version.ref = "matrix" }
matrix-memory-canary = { group = "com.tencent.matrix", name = "matrix-memory-canary", version.ref = "matrix" }
matrix-battery-canary = { group = "com.tencent.matrix", name = "matrix-battery-canary", version.ref = "matrix" }
matrix-resource-canary-android = { group = "com.tencent.matrix", name = "matrix-resource-canary-android", version.ref = "matrix" }
matrix-resource-canary-common = { group = "com.tencent.matrix", name = "matrix-resource-canary-common", version.ref = "matrix" }
matrix-resource-canary-analyzer = { group = "com.tencent.matrix", name = "matrix-resource-canary-analyzer", version.ref = "matrix" }
godeye-core = { group = "com.github.Kyson.AndroidGodEye", name = "godeye-core", version.ref = "godeye" }
godeye-monitor = { group = "com.github.Kyson.AndroidGodEye", name = "godeye-monitor", version.ref = "godeye" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
metrics-performance = { group = "androidx.metrics", name = "metrics-performance", version.ref = "metricsPerformance" }
tracing = { group = "androidx.tracing", name = "tracing", version.ref = "tracing" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
