plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.example.myapplication'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.example.myapplication"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation project(':utils')
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation libs.appcompat
    implementation libs.material
    debugImplementation 'io.github.didi.dokit:dokitx:3.5.0'
    releaseImplementation 'io.github.didi.dokit:dokitx-no-op:3.5.0'
    implementation 'com.arthenica:ffmpeg-kit-full:6.0-2'
    implementation 'com.google.android.exoplayer:exoplayer:2.19.1'
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
